### ISSUE TITLE
[US-34] Create a job post

### ISSUE THREAD

**Issue by z-bruce** [haris2055/SOEN390#116]
As a registered user, I want to be able to create a job post for an open job position, so that people can view the job posting and apply to it if they choose to.
Note: The job post must consist of the:
- Company name
- Job type (full-time, part-time, internship)
- Job description
- Application submission deadline
- Application submission type (apply in-app or through third-party app - if through third-party app, supply link to job post)

MoSCoW: M
Business Value: XXL
Risk: M

**Comment by Nijaoui-Wassim** [comment]
Sprint 2 Finalization #121 PR accomplished this
