### ISSUE TITLE
[US-36] Manage/edit a job post

### ISSUE THREAD

**Issue by z-bruce** [haris2055/SOEN390#118]
As a registered user, I want to be able to edit a job post that I have created, so that I could correct or update any job post that I create.

MoSCoW: M
Business Value: XL
Risk: M

**Comment by Nijaoui-Wassim** [comment]
Sprint 2 Finalization #121 PR accomplished this

**Comment by z-bruce** [comment]
This user story was completed via PR #172 (Job Post Features).
