### ISSUE TITLE
[US-47] Redirect to Job Post in Third-Party App

### ISSUE THREAD

**Issue by VCastelli** [haris2055/SOEN390#142]
Epic: #78 

As a registered user, if I must apply for a position in a job post through a third-party app, I want to be redirected to the third-party app’s job post through the initial job post found in the system.

MoSCoW: M
Business Value:XXL
Risk: L

**Comment by z-bruce** [comment]
This user story was completed via PR #172 (Job Post Features). For 'external' Job Posts, the Apply button redirects the user to the link specified by the poster of the job.
