### ISSUE TITLE
[US-6] Create User Profile 

### ISSUE THREAD

**Issue by VCastelli** [haris2055/SOEN390#86]
Epic: #72 

As a registered user, I want to create my own user profile, so that I can make my profile page available to other users. 

Note: The user profile must consist of: 
- [ ] Profile picture 
- [ ] Name 
- [ ] Education 
- [ ] Work experience 
- [ ] Contact info (optional visibility)
- [ ] List connections 
- [ ] Biography 
- [ ] Volunteering 
- [ ] Skills
- [ ] Recommendations 
- [ ] Courses
- [ ] Projects 
- [ ] Awards
- [ ] Languages

MoSCoW: M 
Business Value: XXL
Risk: M

**Comment by z-bruce** [comment]
This issue was left open as we were considering making enhancements to the implementation of the profile features, however, the team has decided to leave the profile the way that it is currently implemented, so this issue is being closed.
The main functionality was implemented through PR #121.
