### ISSUE TITLE
[US-11] Edit User Profile Page 

### ISSUE THREAD

**Issue by VCastelli** [haris2055/SOEN390#92]
Epic: #72 

As a registered user, I want to edit the contents of the user profile page, so that the information on my user profile page can be corrected if it is wrong or updated if I have new information to add to it.

MoSCoW: M
Business Value: XXL
Risk: M

**Comment by z-bruce** [comment]
This issue was left open as we were considering making enhancements to the implementation of the profile features, however, the team has decided to leave the profile the way that it is currently implemented, so this issue is being closed.
The main functionality was implemented through PR #121.
